export const localizationTexts = {
    'ro': {
        'field.mandatory': '*',
        'field.optional': ' (opțional)',
        'step.department': 'Pasul {0}. Alege categoria de servicii',
        'step.department.done': 'Pasul {0}. Categoria aleasă',
        'step.service': 'Pasul {0}. Alege serviciul dorit',
        'step.service.done': 'Pasul {0}. Serviciul ales',
        'step.slot': 'Pasul {0}. Alege data și ora programării',
        'step.slot.hour': 'Oră programare {0}',
        'step.slot.done': 'Pasul {0}. Data si ora aleasă',
        'step.slot.noSlots': 'Toate intervalele de programare au fost deja rezervate. Te rugăm să încerci mai târziu.',
        'step.personalInfo': 'Pasul {0}. Completează datele personale',
        'step.personalInfo.done': 'Pasul {0}. Date personale',
        'step.confirmation': 'Pasul {0}. Confirmarea programării',
        'service.price': 'Preț',
        'service.address': 'Locație',
        'service.specialist': 'Specialist',
        'service.duration': 'Durată',
        'customer.name': 'Nume',
        'customer.mobile': 'Numar mobil',
        'customer.email': 'Email',
        'customer.acceptTerms': 'Am citit, înteles și sunt de acord cu termenii și condițiile serviciului de programare',
        'ctaBooking': 'Programează',
        'booking.error': 'Nu s-a putut crea programarea. Te rugam să încerci din nou.',
        'booking.success': 'Programare creată cu succes.',
        'booking.ref': 'Numar confirmare',
        'booking.title': 'Programare online',
        'filter.specialists': 'Filtrează dupa specialiști',
        'filter.locations': 'Filtrează dupa locații',
        'error.name_empty': 'Numele trebuie să conțină cel puțin 3 caractere.',
        'error.mobile_empty': 'Numărul de telefon mobil este obligatoriu.',
        'error.email_empty': 'Adresa de email este obligatorie.',
        'error.terms_not_accepted': 'Trebuie să accepți termenii și condițiile.',
        'error.name_too_long': 'Numele trebuie să aibă maximum 30 de caractere.',
        'error.name_invalid': 'Numele poate conține doar litere și cifre, fără diacritice.',
        'error.mobile_invalid': 'Număr de telefon invalid.',
        'error.email_invalid': 'Formatul adresei de email este invalid.',
        'error.generic': 'A apărut o eroare neașteptată. Te rugăm să încerci mai târziu.',
        'booking.details.greeting': 'Salut, vezi detaliile programării tale.',
        'booking.details.customer': 'Datele tale',
        'booking.details.appointment': 'Detalii programare',
        'booking.details.dateTime': 'Data și ora programării',
        'cta.reschedule': 'Reprogramează',
        'cta.cancel': 'Anulează programarea',
        'loading.bookingDetails': 'Se încarcă detaliile programării...',
        'booking.details.loading': 'Se încarcă detaliile programării...',
        'booking.details.error': 'Nu am putut încărca detaliile programării.',
        'booking.details.notFound': 'Programarea nu mai există sau a expirat.',

        'reschedule.step.current': 'Pasul {0}. Programarea curentă',
        'reschedule.step.newSlot': 'Pasul {0}. Alege noua dată și oră',
        'reschedule.step.newSlot.done': 'Pasul {0}. Noua dată și oră',
        'reschedule.step.confirmation': 'Pasul {0}. Confirmarea reprogramării',
        'reschedule.cta': 'Reprogramează',
        'reschedule.terms': 'Am citit și sunt de acord cu termenii și condițiile pentru reprogramare.',
        'reschedule.success': 'Reprogramarea a fost creată cu succes.',
        'reschedule.ref': 'Număr confirmare',
        'reschedule.error': 'Nu s-a putut reprograma. Te rugăm să încerci din nou.',

        'cancel.confirm': 'Ești sigur că vrei să anulezi programarea?',
        'cancel.success': 'Programarea a fost anulată cu succes.',
        'cancel.error': 'Nu am putut anula programarea. Te rugăm să încerci din nou.'


    },

    'en': {
        'field.mandatory': '*',
        'field.optional': ' (optional)',
        'step.department': 'Step {0}. Select a service category',
        'step.department.done': 'Step {0}. Selected service category',
        'step.service': 'Step {0}. Choose a service',
        'step.service.done': 'Step {0}. Selected service',
        'step.slot': 'Step {0}. Choose the booking date and time',
        'step.slot.hour': 'Appointment time {0}',
        'step.slot.done': 'Step {0}. Booking date and time',
        'step.slot.noSlots': 'All scheduling slots have already been booked. Please try again later.',
        'step.personalInfo': 'Step {0}. Fill personal information',
        'step.personalInfo.done': 'Step {0}. Personal information',
        'step.confirmation': 'Step {0}. Booking confirmation',
        'service.price': 'Price',
        'service.address': 'Location',
        'service.specialist': 'Specialist',
        'service.duration': 'Duration',
        'customer.name': 'Name',
        'customer.mobile': 'Mobile number',
        'customer.email': 'Email',
        'customer.acceptTerms': 'I have read, understood and I accept the booking service terms and conditions',
        'ctaBooking': 'Create booking',
        'booking.error': 'Could not create the boooking. Please try again.',
        'booking.success': 'Your booking was created with success.',
        'booking.ref': 'Confirmation reference',
        'booking.title': 'Online booking',
        'filter.specialists': 'Filter by specialists',
        'filter.locations': 'Filter by locations',
        'error.name_empty': 'The name must contain at least 3 characters.',
        'error.mobile_empty': 'The mobile phone number is required.',
        'error.email_empty': 'The email address is required.',
        'error.terms_not_accepted': 'You must accept the terms and conditions.',
        'error.name_too_long': 'The name must have a maximum of 30 characters.',
        'error.name_invalid': 'The name may contain only letters and numbers, without diacritics.',
        'error.mobile_invalid': 'Invalid phone number.',
        'error.email_invalid': 'Invalid email format.',
        'error.generic': 'Unexpected error, please try again later.',
        'booking.details.greeting': 'Hi, here are your booking details.',
        'booking.details.customer': 'Your details',
        'booking.details.appointment': 'Booking details',
        'booking.details.dateTime': 'Booking date and time',
        'cta.reschedule': 'Reschedule',
        'cta.cancel': 'Cancel booking',
        'loading.bookingDetails': 'Loading booking details...',
        'booking.details.loading': 'Loading booking details...',
        'booking.details.error': 'Could not load booking details.',
        'booking.details.notFound': 'Booking does not exist or has expired.',

        'reschedule.step.current': 'Step {0}. Current booking',
        'reschedule.step.newSlot': 'Step {0}. Choose new date and time',
        'reschedule.step.newSlot.done': 'Step {0}. New date and time',
        'reschedule.step.confirmation': 'Step {0}. Reschedule confirmation',
        'reschedule.cta': 'Reschedule',
        'reschedule.terms': 'I have read and agree with the terms and conditions for rescheduling.',
        'reschedule.success': 'Reschedule was created successfully.',
        'reschedule.ref': 'Confirmation number',
        'reschedule.error': 'Could not reschedule. Please try again.',

        'cancel.confirm': 'Are you sure you want to cancel this booking?',
        'cancel.success': 'The booking was cancelled successfully.',
        'cancel.error': 'We could not cancel the booking. Please try again.'


    }
};
