export const localizationTexts = {
    'ro': {
        'step.department': 'Pasul {0}. Alege categoria de servicii',
        'step.department.done': 'Pasul {0}. Categoria aleasă',
        'step.service': 'Pasul {0}. Alege serviciul dorit',
        'step.service.done': 'Pasul {0}. Serviciul ales',
        'step.slot': 'Pasul {0}. Alege data și ora programării',
        'step.slot.done': 'Pasul {0}. Data si ora aleasă',
        'step.personalInfo': 'Pasul {0}. Completează datele personale',
        'step.personalInfo.done': 'Pasul {0}. Date personale',
        'step.confirmation': 'Pasul {0}. Confirmarea programării',
        'service.price': 'Preț',
        'service.address': 'Locație',
        'service.specialist': 'Specialist',
        'service.duration': 'Durata',
        'customer.name': 'Nume',
        'customer.mobile': 'Numar mobil',
        'customer.email': 'Email',
        'customer.acceptTerms': 'Am citit, înteles și sunt de acord cu termenii și condițiile serviciului de programare',
        'ctaBooking': 'Programează',
        'booking.error': 'Nu s-a putut crea programarea. Te rugam să încerci din nou.',
        'booking.success': 'Programare creată cu succes.',
        'booking.ref': 'Numar confirmare',
        'booking.title': 'Programare online',
        'filter.specialists': 'Filtrează dupa specialiști',
        'filter.locations': 'Filtreaza dupa locații',
        'error.name_empty': 'Numele trebuie sa aibă cel putin 3 litere',
        'error.mobile_empty': 'Numarul de mobil este obligatoriu',
        'error.email_empty': 'Emailul este obligatoriu',
        'error.terms_not_accepted': 'Termenii și conditiile sunt obligatoriu a fi acceptate',
        'error.name_too_long': 'Numele trebuie să fie mai scurt de 30 caractere',
        'error.name_invalid': 'Numele poate conține numai litere si cifre, fara diacritice',
        'error.mobile_invalid': 'Numar mobil invalid',
        'error.email_invalid': 'Email format invalid'
    },

    'en': {
        'step.department': 'Step {0}. Select a service category',
        'step.department.done': 'Step {0}. Selected service category',
        'step.service': 'Step {0}. Choose a service',
        'step.service.done': 'Step {0}. Selected service',
        'step.slot': 'Step {0}. Choose the booking date and time',
        'step.slot.done': 'Step {0}. Booking date and time',
        'step.personalInfo': 'Step {0}. Fill personal information',
        'step.personalInfo.done': 'Step {0}. Personal information',
        'step.confirmation': 'Step {0}. Booking confirmation',
        'service.price': 'Price',
        'service.address': 'Location',
        'service.specialist': 'Specialist',
        'service.duration': 'Duration',
        'customer.name': 'Name',
        'customer.mobile': 'Mobile number',
        'customer.email': 'Email',
        'customer.acceptTerms': 'I have read, understood and I accept the booking service terms and conditions',
        'ctaBooking': 'Create booking',
        'booking.error': 'Could not create the boooking. Please try again.',
        'booking.success': 'Your booking was created with success.',
        'booking.ref': 'Confirmation reference',
        'booking.title': 'Online booking',
        'filter.specialists': 'Filter by specialists',
        'filter.locations': 'Filter by locations',
        'error.name_empty': 'Name needs to have at least 3 letters',
        'error.mobile_empty': 'Mobile number cannot be empty',
        'error.email_empty': 'Email cannot be empty',
        'error.terms_not_accepted': 'Terms and Conditions, Privacy Policy acceptance is mandatory',
        'error.name_too_long': 'Name needs to be less than 30 letters',
        'error.name_invalid': 'Name can contain only letters and digits',
        'error.mobile_invalid': 'Mobile number invalid',
        'error.email_invalid': 'Invalid email format'
    }
};
